# dependabot.yml reference: https://docs.github.com/en/free-pro-team@latest/github/administering-a-repository/configuration-options-for-dependency-updates
version: 2
updates:
  # Maintain Python dependencies for the jupyterhub/k8s-hub image
  - package-ecosystem: pip
    directory: "/images/hub"
    schedule: &schedule
      interval: daily
      time: "05:00"
      timezone: "Etc/UTC"
    open-pull-requests-limit: 4
    versioning-strategy: lockfile-only
    labels:
      - maintenance
      - dependencies

  # Maintain dependencies in our GitHub Workflows
  - package-ecosystem: "github-actions"
    directory: "/"  # This should be / rather than .github/workflows
    schedule: *schedule
    labels:
      - maintenance
      - dependencies
