# This configuration maps local.jovyan.org to JupyterHub's proxy-public
# Service, and has Pebble validate HTTP-01 on a service port matching
# Traefik's pod HTTP port.
#
# ref: https://github.com/jupyterhub/pebble-helm-chart/blob/HEAD/pebble/values.yaml
#
pebble:
  config:
    pebble:
      httpPort: 8080

coredns:
  corefileSegment: |-
    template ANY ANY local.jovyan.org {
      answer "{{ .Name }} 60 IN CNAME proxy-public.{$PEBBLE_NAMESPACE}.svc.cluster.local"
    }
