{{- if .Values.scheduler.enabled -}}
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: scheduler
  labels:
    {{- include "jupyterhub.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.scheduler.replicas }}
  template:
    metadata:
      annotations:
        # This lets us autorestart when the configmap changes!
        checksum/config-map: {{ include (print $.Template.BasePath "/scheduler/configmap.yaml") . | sha256sum }}
      labels:
        {{- /* Changes here will cause the Deployment to restart the pods. */}}
        {{- include "jupyterhub.matchLabels" . | nindent 8 }}
    spec:
      serviceAccountName: scheduler
      containers:
      - name: scheduler
        image: gcr.io/google_containers/kube-scheduler-amd64:v1.10.4
        command:
        - /usr/local/bin/kube-scheduler
        - --address=0.0.0.0
        - --scheduler-name=jupyterhub-scheduler
        - --policy-configmap=scheduler
        - --policy-configmap-namespace={{ .Release.Namespace }}
        - --leader-elect=true
        - --leader-elect-resource-lock=configmaps
        - --lock-object-name=scheduler
        - --lock-object-namespace={{ .Release.Namespace }}
        - --v=4
        livenessProbe:
          httpGet:
            path: /healthz
            port: 10251
          initialDelaySeconds: 15
        readinessProbe:
          httpGet:
            path: /healthz
            port: 10251
        resources:
          requests:
            cpu: 1
            memory: 2Gi
{{- end }}
