{{- if .Values.scheduler.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: scheduler
  namespace: kube-system
  labels:
    {{- include "jupyterhub.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.scheduler.replicas }}
  selector:
    matchLabels:
      {{- include "jupyterhub.matchLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- /* Changes here will cause the Deployment to restart the pods. */}}
        {{- include "jupyterhub.matchLabels" . | nindent 8 }}
        hub.jupyter.org/pod-category: "core"
      annotations:
        # This lets us autorestart when the configmap changes!
        checksum/config-map: {{ include (print $.Template.BasePath "/scheduler/configmap.yaml") . | sha256sum }}
    spec:
      {{- if .Values.rbac.enabled }}
      serviceAccountName: scheduler
      {{- end }}
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - preference:
                matchExpressions:
                  - key: hub.jupyter.org/node-purpose
                    operator: In
                    values:
                      - core
              weight: 10
      containers:
        - name: scheduler
          image: {{ include "jupyterhub.scheduler.image" . }}
          command:
            - /usr/local/bin/kube-scheduler
            - --address=0.0.0.0
            - --scheduler-name=scheduler
            - --policy-configmap=scheduler
            - --policy-configmap-namespace=kube-system
            - --leader-elect=false
            - --leader-elect-resource-lock=configmaps
            - --lock-object-name=scheduler
            - --lock-object-namespace=kube-system
            - --v=4
          livenessProbe:
            httpGet:
              path: /healthz
              port: 10251
            initialDelaySeconds: 15
          readinessProbe:
            httpGet:
              path: /healthz
              port: 10251
          resources:
            requests:
              cpu: 50m
              memory: 512Mi
{{- end }}
