{{- if .Values.scheduler.enabled -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: scheduler
{{- if .Values.rbac.enabled }}
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: scheduler
subjects:
- kind: ServiceAccount
  name: scheduler
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: system:kube-scheduler
  apiGroup: rbac.authorization.k8s.io
{{- end }}
{{- end }}
