{{- if .Values.scheduling.jupyterhubScheduler.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jupyterhub-scheduler
  namespace: kube-system
  labels:
    {{- include "jupyterhub.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.scheduling.jupyterhubScheduler.replicas }}
  selector:
    matchLabels:
      {{- include "jupyterhub.matchLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- /* Changes here will cause the Deployment to restart the pods. */}}
        {{- include "jupyterhub.matchLabels" . | nindent 8 }}
        hub.jupyter.org/pod-kind: "core"
      annotations:
        # This lets us autorestart when the configmap changes!
        checksum/config-map: {{ include (print $.Template.BasePath "/scheduling/scheduler/configmap.yaml") . | sha256sum }}
    spec:
      {{- if .Values.rbac.enabled }}
      serviceAccountName: jupyterhub-scheduler
      {{- end }}
      affinity:
        {{- $_ := merge (dict "podKind" "core") . }}
        {{- include "jupyterhub.nodeAffinity" $_ | nindent 8 }}
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: component
                      operator: In
                      values: ["scheduler"]
                topologyKey: kubernetes.io/hostname
              weight: 100
      containers:
        - name: jupyterhub-scheduler
          image: {{ include "jupyterhub.scheduler.image" . }}
          command:
            - /usr/local/bin/kube-scheduler
            - --scheduler-name=jupyterhub-scheduler
            - --policy-configmap=jupyterhub-scheduler
            - --lock-object-name=jupyterhub-scheduler
            - --v=4
          livenessProbe:
            httpGet:
              path: /healthz
              port: 10251
            initialDelaySeconds: 15
          readinessProbe:
            httpGet:
              path: /healthz
              port: 10251
          resources:
            requests:
              cpu: 50m
              memory: 512Mi
{{- end }}
