{{- if .Values.placeholder.userDummyTesting.enabled -}}
{{- $_ := merge (dict "componentLabel" "user-dummy") . -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-dummy
  labels:
    {{- include "jupyterhub.labels" $_ | nindent 4 }}
spec:
  replicas: {{ .Values.placeholder.userDummyTesting.replicas }}
  selector:
    matchLabels:
      {{- include "jupyterhub.matchLabels" $_ | nindent 6 }}
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 100%
      maxSurge: 100%
  template:
    metadata:
      labels:
        {{- /* Changes here will cause the Deployment to restart the pods. */}}
        {{- include "jupyterhub.matchLabels" $_ | nindent 8 }}
        hub.jupyter.org/pod-category: "user"
    spec:
      {{- if .Values.scheduling.jupyterhubScheduler.enabled }}
      schedulerName: jupyterhub-scheduler
      {{- end }}
      tolerations:
        {{- /* FIXME: '/' https://issuetracker.google.com/issues/77240642 */}}
        - key: hub.jupyter.org_dedicated
          operator: Equal
          value: user
          effect: NoSchedule
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - preference:
                matchExpressions:
                  - key: hub.jupyter.org/node-purpose
                    operator: In
                    values:
                      - user
              weight: 10
      terminationGracePeriodSeconds: 0
      automountServiceAccountToken: false
      containers:
        - name: pause
          image: {{ .Values.prePuller.pause.image.name }}:{{ .Values.prePuller.pause.image.tag }}
          resources:
            {{- include "jupyterhub.placeholder.resources" . | nindent 12 }}
{{- end }}
