apiVersion: scheduling.k8s.io/v1alpha1
kind: PriorityClass
metadata:
  name: default-priority
value: 10
globalDefault: true
description: "Used by placeholder pods to be evicted by important pods but still be able to trigger scale up of nodes."
---
apiVersion: scheduling.k8s.io/v1alpha1
kind: PriorityClass
metadata:
  name: placeholder-priority
value: 0
globalDefault: false
description: "Used by placeholder pods to be evicted by important pods but still be able to trigger scale up of nodes."